name: DaimonosPhotos
favicon: null
layout_spectrum: 0.23082303698174655
typography_spectrum: 0.7736506087239832
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7181247188709676
  lightness: 0.9955777826253325
  saturation: 0.41392606659792364
  rhythmicContrast: 0.3447297017555684
purpose: []
